---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: homepage
    helm.sh/chart: app-template-4.0.1
  namespace: intel-system
data:
  bookmarks.yaml: |
    - Homelab:
      - Documentation:
        - href: https://homelab.khuedoan.com
          icon: google-docs.svg
      - Public homelab repository:
        - href: https://github.com/khuedoan/homelab
          icon: github.svg
    - Managed services:
      - Cloudflare:
        - href: https://dash.cloudflare.com
          icon: cloudflare.svg
      - Terraform Cloud:
        - href: https://app.terraform.io
          icon: terraform.svg
    - Infrastructure:
      - Router:
        - href: https://192.168.1.1
          icon: router.svg
      - Proxmox:
        - href: https://proxmox:8006
          icon: proxmox.svg
      - Google Cloud:
        - href: https://console.cloud.google.com
          icon: google-cloud-platform.svg
      - Oracle Cloud:
        - href: https://cloud.oracle.com
          icon: oracle-cloud.svg
  services.yaml: |
    - Popular:
      - Matrix:
          href: https://chat.khuedoan.com
          description: Chat client
          icon: element.svg
      - Jellyfin:
          href: https://jellyfin.khuedoan.com
          description: Media system (movies, music, etc.)
          icon: jellyfin.svg
      - Jellyseerr:
          href: https://jellyseerr.khuedoan.com
          description: Request media
          icon: jellyseerr.svg
      - Paperless:
          href: https://paperless.khuedoan.com
          description: Document management system
          icon: paperless.svg
    - Management:
      - Transmission:
          href: https://transmission.khuedoan.com
          description: Bittorrent client
          icon: transmission.svg
      - Prowlarr:
          href: https://prowlarr.khuedoan.com
          description: Indexer manager
          icon: prowlarr.svg
      - Radarr:
          href: https://radarr.khuedoan.com
          description: Movie manager
          icon: radarr.svg
      - Sonarr:
          href: https://sonarr.khuedoan.com
          description: TV show manager
          icon: sonarr.svg
      - Kanidm:
          href: https://auth.khuedoan.com
          description: Identity management
          icon: https://auth.khuedoan.com/pkg/img/logo-square.svg
    - Development:
      - Gitea:
          href: https://git.khuedoan.com
          description: Git forge
          icon: gitea.svg
      - Woodpecker:
          href: https://ci.khuedoan.com
          description: Continuous integration
          icon: woodpecker-ci.svg
      - ArgoCD:
          href: https://argocd.khuedoan.com
          description: Continuous deployment
          icon: argocd.svg
      - Registry:
          href: https://registry.khuedoan.com
          description: Container registry
          icon: docker.svg
      - Grafana:
          href: https://grafana.khuedoan.com
          description: Observability dashboards
          icon: grafana.svg
    - Utilities:
      - Excalidraw:
          href: https://draw.khuedoan.com
          description: Virtual whiteboard
          icon: excalidraw.svg
      - Speedtest:
          href: https://speedtest.khuedoan.com
          description: Internal network speed test
          icon: openspeedtest.png
  settings.yaml: |
    background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
    cardBlur: md
    theme: dark
    headerStyle: boxed
    hideVersion: true
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster vsval"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - longhorn:
        expanded: true
        total: true
        # Shows the node names as labels
        labels: true
        # Show the nodes
        nodes: true
    - search:
        provider: google
        target: _blank
---
# Source: homepage/charts/app-template/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: homepage
  labels:
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: homepage
    app.kubernetes.io/service: homepage
    helm.sh/chart: app-template-4.0.1
  namespace: intel-system
spec:
  type: ClusterIP
  ports:
    - port: 31310
      targetPort: 31310
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/name: homepage
---
# Source: homepage/charts/app-template/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  labels:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: homepage
    helm.sh/chart: app-template-4.0.1
  namespace: intel-system
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/name: homepage
      app.kubernetes.io/instance: homepage
  template:
    metadata:
      annotations: 
        checksum/configMaps: f374214338472936a6d5627c27f1b74d020db05bfc85f61457d3ac8cad955eb6
      labels: 
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: homepage
        app.kubernetes.io/name: homepage
    spec: 
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers: 
        - image: ghcr.io/gethomepage/homepage:v1.2.0
          name: main
          volumeMounts:
          - mountPath: /app/config/settings.yaml
            name: config
            subPath: settings.yaml
          - mountPath: /app/config/widgets.yaml
            name: config
            subPath: widgets.yaml
          - mountPath: /app/config/services.yaml
            name: config
            subPath: services.yaml
          - mountPath: /app/config/bookmarks.yaml
            name: config
            subPath: bookmarks.yaml
      volumes: 
        - configMap:
            name: homepage-config
          name: config
---
# Source: homepage/charts/app-template/templates/common.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  labels:
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: homepage
    helm.sh/chart: app-template-4.0.1
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  namespace: intel-system
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "homepage.vsval.intel.com"
      secretName: "homepage-vsval-tls-certificate"
  rules:
    - host: "homepage.vsval.intel.com"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: main
                port:
                  number: 31310
