app-template:
  controllers:
    main:
      containers:
        homepage:
          env:
          - name: HOMEPAGE_ALLOWED_HOSTS
            value: homepage.vsval.intel.com
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          image:
            repository: ghcr.io/gethomepage/homepage
            tag: v1.2.0
  service:
    main:
      ports:
        http:
          port: 31310
          targetPort: 3000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      hosts:
        - host: homepage.vsval.intel.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: homepage
                port: 31310
      tls:
        - hosts:
            - homepage.vsval.intel.com
          secretName: homepage-vsval-tls-certificate
  persistence:
    config:
      enabled: true
      type: configMap
      name: homepage
      globalMounts:
        - path: /app/config/settings.yaml
          subPath: settings.yaml
        - path: /app/config/widgets.yaml
          subPath: widgets.yaml
        - path: /app/config/services.yaml
          subPath: services.yaml
        - path: /app/config/bookmarks.yaml
          subPath: bookmarks.yaml
        - path: /app/config/kubernetes.yaml
          subPath: kubernetes.yaml
        - path: /app/config/docker.yaml
          subPath: docker.yaml
        - path: /app/config/custom.js
          subPath: custom.js
        - path: /app/config/custom.css
          subPath: custom.css
  configMaps:
    homepage:
      enabled: true
      data:
        docker.yaml: ""
        kubernetes.yaml: |
          mode: cluster
        custom.css: ""
        custom.js: ""
        settings.yaml: |
          providers:
            longhorn:
              username: "admin"
              password: "adminintel123!"
              url: longhorn.vsval.intel.com
          background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
          cardBlur: md
          theme: dark
          headerStyle: boxed
          hideVersion: true
        widgets.yaml: |
          - kubernetes:
              cluster:
                show: true
                cpu: true
                memory: true
                showLabel: true
                label: "cluster vsval"
              nodes:
                show: true
                cpu: true
                memory: true
                showLabel: true
          - longhorn:
              expanded: true
              total: true
              # Shows the node names as labels
              labels: true
              # Show the nodes
              nodes: true
          - search:
              provider: google
              target: _blank
        services.yaml: |
          - Popular:
            - Matrix:
                href: https://chat.khuedoan.com
                description: Chat client
                icon: element.svg
            - Jellyfin:
                href: https://jellyfin.khuedoan.com
                description: Media system (movies, music, etc.)
                icon: jellyfin.svg
            - Jellyseerr:
                href: https://jellyseerr.khuedoan.com
                description: Request media
                icon: jellyseerr.svg
            - Paperless:
                href: https://paperless.khuedoan.com
                description: Document management system
                icon: paperless.svg
          - Management:
            - Transmission:
                href: https://transmission.khuedoan.com
                description: Bittorrent client
                icon: transmission.svg
            - Prowlarr:
                href: https://prowlarr.khuedoan.com
                description: Indexer manager
                icon: prowlarr.svg
            - Radarr:
                href: https://radarr.khuedoan.com
                description: Movie manager
                icon: radarr.svg
            - Sonarr:
                href: https://sonarr.khuedoan.com
                description: TV show manager
                icon: sonarr.svg
            - Kanidm:
                href: https://auth.khuedoan.com
                description: Identity management
                icon: https://auth.khuedoan.com/pkg/img/logo-square.svg
          - Development:
            - Gitea:
                href: https://git.khuedoan.com
                description: Git forge
                icon: gitea.svg
            - Woodpecker:
                href: https://ci.khuedoan.com
                description: Continuous integration
                icon: woodpecker-ci.svg
            - ArgoCD:
                href: https://argocd.khuedoan.com
                description: Continuous deployment
                icon: argocd.svg
            - Registry:
                href: https://registry.khuedoan.com
                description: Container registry
                icon: docker.svg
            - Grafana:
                href: https://grafana.khuedoan.com
                description: Observability dashboards
                icon: grafana.svg
          - Utilities:
            - Excalidraw:
                href: https://draw.khuedoan.com
                description: Virtual whiteboard
                icon: excalidraw.svg
            - Speedtest:
                href: https://speedtest.khuedoan.com
                description: Internal network speed test
                icon: openspeedtest.png
        bookmarks.yaml: |
          - Homelab:
            - Documentation:
              - href: https://homelab.khuedoan.com
                icon: google-docs.svg
            - Public homelab repository:
              - href: https://github.com/khuedoan/homelab
                icon: github.svg
          - Managed services:
            - Cloudflare:
              - href: https://dash.cloudflare.com
                icon: cloudflare.svg
            - Terraform Cloud:
              - href: https://app.terraform.io
                icon: terraform.svg
          - Infrastructure:
            - Router:
              - href: https://192.168.1.1
                icon: router.svg
            - Proxmox:
              - href: https://proxmox:8006
                icon: proxmox.svg
            - Google Cloud:
              - href: https://console.cloud.google.com
                icon: google-cloud-platform.svg
            - Oracle Cloud:
              - href: https://cloud.oracle.com
                icon: oracle-cloud.svg
