---
- name: 'Install gpg'
  ansible.builtin.apt:
    name:
    - gpg
    update_cache: true
  become: true
  register: aptrc
  until: aptrc is success
  retries: 5
  delay: 10

- name: 'Add GPG key'
  ansible.builtin.apt_key:
    url: "{{ k8s_repo_key_url['debian'] }}"
    state: present
  become: true
  register: aptrc
  until: aptrc is success
  retries: 5
  delay: 10

- name: 'Add k8s repository to apt'
  ansible.builtin.apt_repository:
    repo: "deb {{ k8s_repo_url['debian'] }} kubernetes-xenial main"
    state: present
  become: true

- name: 'Install kubeadm, kubelet, and kubectl'
  ansible.builtin.apt:
    name:
    - "kubeadm={{ k8s_version }}-*"
    - "kubelet={{ k8s_version }}-*"
    - "kubectl={{ k8s_version }}-*"
    update_cache: true
    allow_downgrade: true
  become: true
  register: aptrc
  until: aptrc is success
  retries: 5
  delay: 10
