---
- name: Install Kubernetes addons
  hosts: localhost
  roles:
    - packages

- name: Create Kubernetes repository
  hosts: metal
  roles:
    - packages
    - prerequisites
    - k3s

- name: Install Kubernetes addons
  hosts: localhost
  roles:
    - cilium
