all:
  vars:
    control_plane_endpoint: 10.211.249.10
    load_balancer_ip_pool:
      - 10.123.235.205/32
      - 10.123.235.206/32
      - 10.123.235.207/32
      - 10.123.235.208/32
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.211.249.10, mac: '52:54:00:a1:aa:fb', disk: vda, network_interface: eth0}
        metal1: {ansible_host: 10.211.249.86, mac: '52:54:00:1b:c3:1d', disk: vda, network_interface: eth0}
        metal2: {ansible_host: 10.211.249.190, mac: '52:54:00:4c:f4:47', disk: vda, network_interface: eth0}

