k3s_version: v1.30.4+k3s1
k3s_config_file: /etc/rancher/k3s/config.yaml
k3s_token_file: /etc/rancher/node/password
k3s_service_file: /etc/systemd/system/k3s.service
k3s_data_dir: /var/lib/rancher/k3s
k3s_kubeconfig_file: /etc/rancher/k3s/k3s.yaml
k3s_server_config:
  tls-san:
    - "{{ control_plane_endpoint }}"
  disable:
    - local-storage
    - servicelb
    - traefik
  disable-helm-controller: true
  disable-kube-proxy: true
  disable-network-policy: true
  flannel-backend: none
  secrets-encryption: true
proxy:
  http_proxy: http://proxy-mu.intel.com:912
  https_proxy: http://proxy-mu.intel.com:912
  no_proxy: caas.intel.com,vsval.intel.com,.vsval.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,cluster.local,127.0.0.0/8,172.16.0.0/12,134.134.0.0/16
