argo-cd:
  global:
    domain: argo.vsval.intel.com
  configs:
    params:
      server.insecure: true
      controller.diff.server.side: true
    cm:
      resource.ignoreResourceUpdatesEnabled: true
      resource.customizations.ignoreResourceUpdates.all: |
        jsonPointers:
          - /status
  redis-ha:
    enabled: true
  server:
    replicas: 2
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      extraTls:
        - hosts:
          - argo.vsval.intel.com
          secretName: argocd-vsval-tls

    metrics: &metrics
      enabled: true
      serviceMonitor:
        enabled: true
  dex:
    enabled: false
  controller:
    metrics: *metrics
    replicas: 1
  repoServer:
    metrics: *metrics
    replicas: 2

  applicationSet:
    replicas: 2
  redis:
    metrics: *metrics

argocd-apps: {}